name: Publish to Git Hub

on:
  push:
    tags:
      - 'release/**'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir tmp
          mvn dependency:copy  -Dartifact=pl.grzeslowski.supla:openhab-supla:LATEST -DoutputDirectory=./
          echo ::set-output name=version::$(ls tmp)
      - name: Show extracted Maven project version
        run: echo "🤩 Released version=${{ steps.project.outputs.version }}"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/${{ steps.project.outputs.version }}
          asset_name: ${{ steps.project.outputs.version }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release of version ${{ steps.project.outputs.version }}"
