name: Release with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Release with Maven
        run: mvn  -Dspotless.check.skip=true -B  release:prepare release:perform
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download latest open-hab
        run: |
          mkdir tmp
          mvn dependency:copy  -Dartifact=pl.grzeslowski.supla:openhab-supla:LATEST -DoutputDirectory=./
          version=$(ls tmp)
          echo ::set-output name=version::$(echo $version)
          echo "🤩 Released version=$version"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/${{ steps.project.outputs.version }}
          asset_name: ${{ steps.project.outputs.version }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release of version ${{ steps.project.outputs.version }}"
