name: Release with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Release with Maven
        run: mvn  -Dspotless.check.skip=true -B  release:prepare release:perform
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download latest open-hab
        id: config
        run: |
          mkdir tmp
          mvn dependency:copy -q -Dartifact=pl.grzeslowski.supla:openhab-supla:LATEST -DoutputDirectory=./tmp
          version=$(ls tmp)
          if [ -z ${version+x} ]; then
            echo "version was not set!"
            exit 12
          fi
          echo "version=$version"
          echo "version=$version" >> $GITHUB_STATE
          
          tag=$(git describe --tags --abbrev=0)
          if [ -z ${tag+x} ]; then
            echo "tag was not set!"
            exit 12
          fi
          echo "tag=$tag"
          echo "tag=$tag" >> $GITHUB_STATE
          echo "🤩 Released version=$version"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/${{ steps.config.outputs.version }}
          asset_name: ${{ steps.config.outputs.version }}
          tag: ${{ steps.config.outputs.tag }}
          overwrite: true
          release_name: Version ${{ steps.config.outputs.version }}
          body: "Release of version ${{ steps.config.outputs.version }}"
