name: Release with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Save Version
        run: |
          MAVEN_MAJOR_VERSION=$(mvn $MAVEN_SETTINGS_OPTS help:evaluate -Dexpression=project.artifact.selectedVersion.majorVersion -q -DforceStdout)
          MAVEN_MINOR_VERSION=$(mvn $MAVEN_SETTINGS_OPTS help:evaluate -Dexpression=project.artifact.selectedVersion.minorVersion -q -DforceStdout)
          MAVEN_PATCH_VERSION=$(mvn $MAVEN_SETTINGS_OPTS help:evaluate -Dexpression=project.artifact.selectedVersion.incrementalVersion -q -DforceStdout)
          MAVEN_VERSION=$MAVEN_MAJOR_VERSION.$MAVEN_MINOR_VERSION.$MAVEN_PATCH_VERSION
      - name: Build with Maven
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/openhab-supla-${MAVEN_VERSION}.jar
          asset_name: openhab-supla-${MAVEN_VERSION}
          tag: ${{ github.ref }}
          overwrite: true
          body: "OpenHAB Addon. Install it in addons folder"
